name: kitmate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  http: ^1.2.1
  flutter_responsive_helper: ^1.0.2
  get_storage: ^2.1.1
  auto_size_text: ^3.0.0
  flutter_easyloading: ^3.0.5
  crypto: ^3.0.3
  flutter_svg: ^2.0.9
  flutter_tts: ^4.0.2
  flutter_timezone: ^2.0.1
  intl: ^0.19.0
  speech_to_text: ^6.5.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/Sf-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/Sf-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/Sf-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/Sf-Pro-Display-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Sf-Pro-Display-Bold.otf
          weight: 700
